#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use ReAnimator;

my $server = ReAnimator->new;

$server->on_connect(
    sub {
        my ($self, $client) = @_;

        warn 'Client connected!';

        $client->on_message(
            sub {
                my ($client, $message) = @_;

                warn "Message from client=$message";
            }
        );

        $client->on_error(
            sub {
                my ($client, $error) = @_;

                warn "Error=$error";
            }
        );

        $client->on_disconnect(
            sub {
                my ($clent) = @_;

                warn "Disconnected!";
            }
        );

        $client->send_message("Hello, world!");
    }
);

$server->on_error(
    sub {
        my ($self, $error) = @_;

        warn "Error=$error";
    }
);

$server->start;
