#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../../lib";

use ReAnimator;

my $server = ReAnimator->new;

$server->on_connect(
    sub {
        my ($self, $client) = @_;

        $client->on_message(
            sub {
                my ($client, $message) = @_;

                $server->send_broadcast_message($message);
            }
        );

        $client->send_message('Welcome!');
    }
);

$server->listen;
