#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use ReAnimator;

ReAnimator->new(
    on_accept => sub {
        my ($self, $client) = @_;

        $client->on_message(
            sub {
                my ($client, $message) = @_;

                $self->send_broadcast_message($message);
            }
        );

        $client->send_message('Welcome!');
    }
)->listen->start;
