#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

$SIG{INT} = $SIG{TERM} = sub { exit 0 };

use EventReactor;

my $buffer = {};

EventReactor->new(
    on_accept => sub {
        my ($self, $atom) = @_;

        $atom->on_read(
            sub {
                my ($self, $chunk) = @_;

                $buffer->{"$self"} .= $chunk;

                if (index($buffer->{"$self"}, "\x0d\x0a\x0d\x0a") >= 0) {
                    delete $buffer->{"$self"};

                    $atom->write("HTTP/1.1 200 OK\x0d\x0a"
                          . "Connection: keep-alive\x0d\x0a\x0d\x0a");
                }
            }
        );
    }
)->listen->start;

1;
